### ISSUE TITLE
Does isochrone only work in Switzerland?

### ISSUE THREAD

**Issue by duleise** [zumbov2/walkalytics#1]
Codes in the examples work fine for me.
But when I change it to places in Stockholm, it stopped working with this error
`Error: no points-of-interest found`
Is it working only in certain regions?
Thanks.

**Comment by zumbov2** [comment]
Hey @duleise 

Forgive me for never responding. I just wanted to inform you that the API is no longer publicly available. However, I think you've found an alternative in the meantime. ;)

My apologies
Davd
